PREFIX vivo: <http://vivoweb.org/ontology/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

 CONSTRUCT {
   ?URI vivo:freeTextKeyword ?k;
   .
 }
 WHERE {
   BIND(URI(?id) as ?URI)
   VALUES ?num { 0 1 2 3 4 5 }
   BIND (concat("^([^;]*(;|$)){0,",str(?num),"}([^;]*)?(;.*)?") AS ?skipN)
   BIND (replace(?keywords, ?skipN, "$3") AS ?k)
   FILTER (strlen(?k)>0)
   }

CONSTRUCT {
 ?URI a vivo:Organization;
   rdfs:label ?n ;
   vivo:freeTextKeyword ?k ;
   .
 }
 WHERE {
   BIND(URI(?id) as ?URI)
   BIND (STRLANG(?name, "en") AS ?n)
   OPTIONAL { ?URI vivo:freeTextKeyword ?k . }
 }
